---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Dylan Malandain.
--- DateTime: 29/10/2019 02:40
---

if (not nox.is_server) then

    ---@class noxen.lib.ui
    nox.ui = {};

    ---@class Panel
    nox.ui.Panel = {};

    ---@class Window
    nox.ui.Window = {};

    nox.ui.Enum = require 'lib.ui.components.Enum';
    nox.ui.PlaySound = require 'lib.ui.components.Audio';

    nox.ui.EnumHeritage = require 'lib.ui.components.EnumHeritage';
    nox.ui.RenderRectangle = require 'lib.ui.components.rectangle';
    nox.ui.RenderSprite = require 'lib.ui.components.sprite';
    nox.ui.RenderText = require 'lib.ui.components.text';

    nox.ui.BadgeStyle = require 'lib.ui.menu.elements.ItemsBadge';
    nox.ui.Colour = require 'lib.ui.menu.elements.ItemsColour';
    nox.ui.PanelColour = require 'lib.ui.menu.elements.PanelColour';

    ---@class UIItems: BaseObject
    UIItems = nox.class.singleton("UIItems", function(class)
        return class;
    end);

    ---@class UIPanels: BaseObject
    UIPanels = nox.class.singleton("UIPanels", function(class)
        return class;
    end);

    require 'lib.ui.menu.items.UIButton';
    require 'lib.ui.menu.items.UICheckBox';
    require 'lib.ui.menu.items.UILine';
    require 'lib.ui.menu.items.UIList';
    require 'lib.ui.menu.items.UISeparator';
    require 'lib.ui.menu.items.UISlider';
    require 'lib.ui.menu.items.UISliderHeritage';
    require 'lib.ui.menu.items.UISliderProgress';

    require 'lib.ui.menu.panels.UIBoutonPanel';
    require 'lib.ui.menu.panels.UIColourPanel';
    require 'lib.ui.menu.panels.UIGridPanel';
    require 'lib.ui.menu.panels.UIInfoPanel';
    require 'lib.ui.menu.panels.UIPercentagePanel';
    require 'lib.ui.menu.panels.UISpritPanel';
    require 'lib.ui.menu.panels.UIStatisticsPanel';

    require 'lib.ui.menu.windows.UIHeritage';

    require 'lib.ui.menu.MenuController';
    require 'lib.ui.menu.Menu';

    require 'lib.ui.menu.index';

    nox.ui.visual = require 'lib.ui.components.visual';

    local progress <const> = require 'lib.ui.components.progressBar';

    nox.ui.ProgressBar = progress.ProgressBar;
    nox.ui.CancelProgressBar = progress.CancelProgressBar;
end

return nox.ui;
